name: Daily full update (07:00 Zurich)

on:
  schedule:
    - cron: "0 5 * * *"   # 07:00 Europe/Zurich
  workflow_dispatch:

jobs:
  full:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pandas requests pytz

      - name: Fetch FPL data (players_raw, fixtures, teams, player_idlist)
        run: |
          if [ -f scripts/fetch_bootstrap.py ] ; then python scripts/fetch_bootstrap.py ; fi

      - name: Normalize (optional)
        run: |
          if [ -f scripts/normalize_columns.py ] ; then python scripts/normalize_columns.py || true ; fi

      - name: Update deadlines
        run: |
          if [ -f scripts/update_deadlines.py ] ; then python scripts/update_deadlines.py ; fi

      - name: Snapshot players_raw
        run: |
          if [ -f scripts/snapshot_players_raw.py ] ; then python scripts/snapshot_players_raw.py ; fi

      - name: NTI deltas
        run: |
          if [ -f scripts/calc_nti_deltas.py ] ; then python scripts/calc_nti_deltas.py ; fi

      - name: Price change forecast
        run: |
          if [ -f scripts/price_change_forecast.py ] ; then python scripts/price_change_forecast.py ; fi

      - name: Global test
        run: |
          if [ -f scripts/run_global_test.py ] ; then python scripts/run_global_test.py --with-api-check --with-fixtures-diff || true ; fi

      - name: Build directory indexes (snapshots & season)
        run: python scripts/build_indexes.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          git commit -m "chore: daily full update (07:00 Zurich) [skip ci]" || echo "No changes"
          git push
