name: Update players_raw history

on:
  schedule:
    # 07:10 Europe/Zurich ≈ 05:10 UTC (évite les collisions avec d'autres jobs à :00)
    - cron: "10 5 * * *"
  workflow_dispatch:

jobs:
  update-history:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies (no -r)
        run: |
          python -m pip install --upgrade pip
          pip install "pandas>=2.2.3,<2.3" "numpy>=2.1" "requests>=2.32.3,<3" "pytz>=2024.1"

      - name: Debug (branch & last commit)
        run: |
          echo "Python:"; python -V
          git rev-parse --abbrev-ref HEAD
          git log -1 --pretty=oneline || true

      # --- Mise à jour des données (scripts optionnels) ---
      - name: Fetch FPL bootstrap (optional)
        run: |
          if [ -f scripts/fetch_bootstrap.py ]; then
            python scripts/fetch_bootstrap.py
          else
            echo "skip fetch_bootstrap.py"
          fi

      - name: Snapshot players_raw (optional)
        run: |
          if [ -f scripts/snapshot_players_raw.py ]; then
            python scripts/snapshot_players_raw.py
          else
            echo "skip snapshot_players_raw.py"
          fi

      - name: Update players_raw_history (optional)
        run: |
          if [ -f scripts/update_players_raw_history.py ]; then
            python scripts/update_players_raw_history.py
          else
            echo "skip update_players_raw_history.py"
          fi

      - name: Build directory indexes (optional)
        run: |
          if [ -f scripts/build_indexes.py ]; then
            python scripts/build_indexes.py
          else
            echo "skip build_indexes.py"
          fi

      # --- Summaries: toujours régénérer à partir des fichiers produits ci-dessus ---
      - name: Build summaries
        run: python scripts/build_summaries.py

      # --- Commit & push (inclut data/** et summaries/**) ---
      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          git commit -m "chore: update players_raw history + summaries" || echo "No changes"
          git push
