name: Update players_raw_history

on:
  schedule:
    - cron: "0 8 * * *"   # 10:00 Europe/Zurich
    - cron: "0 13 * * *"  # 15:00 Europe/Zurich
    - cron: "0 21 * * *"  # 23:00 Europe/Zurich
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests pytz

      - name: Run update script (snapshots + history)
        run: python scripts/update_players_raw_history.py

      - name: Build directory indexes (snapshots & season)
        run: python scripts/build_indexes.py

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/snapshots/*.csv data/players_raw_history.csv \
                 data/snapshots/index.html data/season/index.html
          git commit -m "chore: update history + indexes [skip ci]" || echo "No changes"
          git push
